# ── Config Example ────────────────────────────────────────────────────────
user: "Grant" # Make same as folder name

# ── File Locations ────────────────────────────────────────────────────────
DB_PATH: 'C:\Users\grechtin\.Harmonoid\Configuration.DB'
KEY: "MEDIA_LIBRARY_DIRECTORIES"
